### ISSUE TITLE
Test naming changed from 1.8 to 1.9 for `float`s

### ISSUE THREAD

**Issue by TWiStErRob** [google/TestParameterInjector#25]
I had this test:
```java
@RunWith(TestParameterInjector.class)
...

@Test
public void testLightStateOnDevice(
	@TestParameter({"45", "0", "-3", "-6", "-9", "-12", "-15", "-18", "-21"}) float angle,
	@TestParameter Preset preset
) {
```
I'm using it for screenshot test recording, so the test names between previous and next versions has to match (otherwise hard to compare screenshots :). When updating from TPI 1.8 to 1.9 my PR failed:
```
java.lang.AssertionError: File src/test/snapshots/images/net.twisterrob.sun.android.logic_SunAngleWidgetViewScreenshotTest_testLightStateOnDevice[45.0,Nice_Preview].png does not exist
```
when inspecting the golden values on master (1.8) I found:
```
net.twisterrob.sun.android.logic_SunAngleWidgetViewScreenshotTest_testLightStateOnDevice[45,Nice_Preview].png
```
Since the only thing changed in the PR was the TPI version number, it's very likely that this had an unintended behavior change:
https://github.com/google/TestParameterInjector/commit/e390bab7bf4c621e54ae7f814ebd405e49d60829#diff-f0f3c84fc90c4da3bd5e1267e7b74d5774029389e86dfe1bba895740b8b886d0R142

**Comment by nymanjens** [comment]
Hi!

Thanks for letting me know.

The behavior you are seeing surprises me, because we have a unit test since 2020-08-05 that tests that

```
    @Test
    public void withFloat(@TestParameter({"1.2", "2"}) float param) {
      testNameToParameterMap.put(testName.getMethodName(), param);
    }
```

gets the test name

```
"withFloat[param=2.0]"
```

which seems to match your use case.

(I can't link to the test because it is removed when exporting to Github due to a dependency on textproto parsing)

I suspect this may be a combination of a change in TestParameterInjector and your JVM being different (e.g. Anroid vs openJDK).

**Comment by nymanjens** [comment]
Hmm, scrap that. Even before this library was open sourced, we had a unit test that ran on an Android emulator that checks that `@TestParameter({"1.2", "2"}) float param)` gives "withFloat[param=2.0]".

Since May 2022, we extended this test with multiple Android versions, starting at SDK version 15.

So that's probably not it either.

**Comment by nymanjens** [comment]
> it's very likely that this had an unintended behavior change:
https://github.com/google/TestParameterInjector/commit/e390bab7bf4c621e54ae7f814ebd405e49d60829#diff-f0f3c84fc90c4da3bd5e1267e7b74d5774029389e86dfe1bba895740b8b886d0R142

(just reading this now)

It feels like it can't be a coincidence, I agree. 

In your case, since parameter names are not present and the value is not an array, it should change `value()` to `valueAsString()`, which in turn becomes `String.valueOf(value());`.

So then `String.valueOf(value())` should give a different result as `MessageFormat.format("{0}", value())`.

From the documentation of `MessageFormat`, it seems like it uses something like `NumberFormat.getInstance(getLocale()).format(argument)` to format the float. That could explain why you are seeing a different result than the Google test infrastructure.

If that's the case, I'd argue this is actually an improvement because it makes the result independent of the locale.

**Comment by TWiStErRob** [comment]
Ok, I'd say fair evaluation, nice! :)
Would you mind adding a hint in the changelog as this is a "breaking" behavior change (depending on usage of course).

**Comment by TWiStErRob** [comment]
Oh, btw my execution is on JVM, not Android devices. [Paparazzi](https://github.com/cashapp/paparazzi) is amazing tech!

**Comment by nymanjens** [comment]
> Would you mind adding a hint in the changelog as this is a "breaking" behavior change (depending on usage of course).

Done in https://github.com/google/TestParameterInjector/commit/cd1575831b100667e8ee68d4408587c8cab5d1db
